name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "gcr.io"

      - name: Build and Push Docker Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }} \
            -t gcr.io/${{ secrets.PROJECT_ID }}/budget-buddy-frontend:latest .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/budget-buddy-frontend:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: budget-buddy-frontend
          image: gcr.io/${{ secrets.PROJECT_ID}}/budget-buddy-frontend
          region: ${{ secrets.GCP_REGION }}
          platform: managed
          allow-authenticated: true
          timeout: 300s

      - name: Allow unauthenticated access
        run: |
          gcloud run services add-iam-policy-binding budget-buddy-frontend \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=europe-west1 \
            --platform=managed
